apiVersion: v1
kind: Service
metadata:
  name: s7valdes-service
  labels:
    app: s7valdes
spec:
  selector:
    app: s7valdes
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort